- platform: template
    lock_status:
      entity_id: lock.front_door_lock
      friendly_name: Front Door Lock Status
      value_template: "{{ states.lock.front_door_lock.attributes.lock_status }}"
